# Generated by Django 4.2 on 2023-10-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0002_notificationmodels_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodels',
            name='settings',
        ),
    ]
